SYSTARG=Linux
<../../mkconfig
SYSTARG=Linux

#Configurable parameters

CONF=emu-g			#default configuration
CONFLIST=emu
CLEANCONFLIST=

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

X11LIBS= -lX11 -lXext	# can remove or override using env section in config files

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS

OBJ=\
	asm-$OBJTYPE.$O\
	osp.$O\
	kproc-pthreads.$O\
	segflush-$OBJTYPE.$O\
	framebuffer.$O\
	devevents.$O\
	devphone.$O\
	alsa_pcm.$O\
	alsa_mixer.$O\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

LIBNAMES=${LIBS:%=lib%.a}
#libs=${LIBS:%=$ROOT/$OBJDIR/lib/lib%.a}

HFILES=\

CFLAGS='-DROOT="'$ROOT'"' -DUSE_PTHREADS -DEMU -I. -I../port -I$ROOT/$SYSTARG/$OBJTYPE/include -I$ROOT/include -I$ROOT/libinterp $CTHREADFLAGS $CFLAGS $EMUOPTIONS
SYSLIBS= $X11LIBS -lm -lcutils -ldl#-lpthread
KERNDATE=`{$NDATE}

default:V:	$O.$CONF

$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBNAMES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

<../port/portmkfile

devfs.$O:	../port/devfs-posix.c
