#! /bin/sh
arm-linux-androideabi-gcc -DANDROID -I$B2G_ROOT/frameworks/wilhelm/include/ -I$B2G_ROOT/hardware/ril/include -I$B2G_ROOT/system/core/include/ -L$B2G_ROOT/out/target/product/hammerhead/obj/lib/ $* -lm
